# Generated by Django 2.0.2 on 2018-10-08 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('medicid', models.BigAutoField(db_column='MedicID', primary_key=True, serialize=False)),
                ('numemedic', models.CharField(blank=True, db_column='NumeMedic', max_length=45, null=True)),
                ('prenumemedic', models.CharField(blank=True, db_column='PrenumeMedic', max_length=45, null=True)),
                ('specializare', models.CharField(blank=True, db_column='Specializare', max_length=45, null=True)),
            ],
            options={
                'db_table': 'medic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('medicamentid', models.BigAutoField(db_column='MedicamentID', primary_key=True, serialize=False)),
                ('denumire', models.TextField(blank=True, db_column='Denumire', null=True)),
            ],
            options={
                'db_table': 'medicament',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('pacientid', models.BigAutoField(db_column='PacientID', primary_key=True, serialize=False)),
                ('cnp', models.BigIntegerField(blank=True, db_column='CNP', null=True)),
                ('numepacient', models.CharField(blank=True, db_column='NumePacient', max_length=45, null=True)),
                ('prenumepacient', models.CharField(blank=True, db_column='PrenumePacient', max_length=45, null=True)),
                ('adresa', models.CharField(blank=True, db_column='Adresa', max_length=45, null=True)),
                ('asigurare', models.CharField(blank=True, db_column='Asigurare', max_length=45, null=True)),
            ],
            options={
                'db_table': 'pacient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consultatie',
            fields=[
                ('pacientid', models.ForeignKey(db_column='PacientID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='spital.Pacient')),
                ('data', models.DateField(blank=True, db_column='Data', null=True)),
                ('diagnostic', models.CharField(blank=True, db_column='Diagnostic', max_length=45, null=True)),
                ('dozamedicament', models.IntegerField(blank=True, db_column='DozaMedicament', null=True)),
            ],
            options={
                'db_table': 'consultatie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicpacient',
            fields=[
                ('medicid', models.ForeignKey(db_column='MedicID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='spital.Medic')),
            ],
            options={
                'db_table': 'medicpacient',
                'managed': False,
            },
        ),
    ]
